### ISSUE TITLE
Webstore link

### ISSUE THREAD

**Issue by vpontin** [CaliAlec/ChromeFBStory#1]
Hi! First, i want to thank you for all the great plugins (like IG Story and Thankful Forever)!

But i'm having difficulties to find this extension in chrome webstore. It was deleted?

I can not compile the extension myself at this time, so if is there any ways to run that plugin, both via chrome extension or userscript I would be grateful!

Thanks in advance and sorry my bad english!

**Comment by CaliAlec** [comment]
@vpontin It was on the Chrome Web Store but removed for some platform violating. I'm trying to get it resolved, but for now, do you know how to manually install Chrome extensions from the dev window? If so, I've attached a complied build.
[ChromeFBStory.zip](https://github.com/CaliAlec/ChromeFBStory/files/1012962/ChromeFBStory.zip)

**Comment by vpontin** [comment]
Yeah, i've installed the unpacked extension, but it didnt load anything and the popup gives me this error:
`Uncaught (in promise) TypeError: Cannot read property 'node' of undefined
    at getStoryTray (popup.js:14855)
    at popup.js:39014
    at <anonymous>`

**Comment by CaliAlec** [comment]
@vpontin Hmm, can you check the response from the FB Stories API? Open your Chrome Dev Tools and switch to the Network tab, then load Facebook. In the filter, type 'graphqlbatch' and click it and check the response. Paste the response so I can check it out (you can delete it after).

**Comment by vpontin** [comment]
@CaliAlec 
`
{"BATCH_0":{"response":{"100006746883643":{"__typename":"User","name":"Vin\u00edcius Pontin da Silva","id":"100006746883643","short_name":"Vin\u00edcius","gender":"MALE","story_bucket":{"edges":[]},"friends_stories_buckets":{"page_info":{"end_cursor":"1281945271842557","has_next_page":false,"has_previous_page":false,"start_cursor":"1514893825210629"},"edges":[{"score":2,"tracking_string":"overridden","node":{"id":"1514893825210629","is_tutorial":true,"other_participant":{"id":"100013803123634","name":"Facebook","short_name":"Facebook","gender":"FEMALE"},"threads":{"edges":[{"node":{"id":"716518278529569","time":1495212765,"thread_status":"PUBLISHED","direct_messages":{"edges":[{"node":{"id":"1938898113011733","url":null,"direct_message_type":"REGULAR","message_media":{"__typename":"Video","is_playable":true,"id":"1537679580035465","height":400,"width":224,"imageVideoThumbnail":{"height":720,"name":null,"scale":1,"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t15.0-10\/s720x720\/17199387_1537680563368700_6568536254504239104_n.jpg?oh=ac98af06e8252fc247dee180b25a38ec&oe=59A83DC9","width":405},"playable_url":"https:\/\/video.xx.fbcdn.net\/v\/t43.1792-2\/16916739_1320566924632867_409461948409708544_n.mp4?efg=eyJybHIiOjE4ODIsInJsYSI6NTEyLCJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&rl=1882&vabr=1046&oh=bfcc53e846e0d60eb4f341efab04b092&oe=592132A3","dashPlayableURL":"https:\/\/graph.facebook.com\/video\/playback\/dash_mpd_debug.mpd?v=1537679580035465&dummy=.mpd","dashPlaylist":"\u003C?xml version=\"1.0\"?>\n\u003CMPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\" minBufferTime=\"PT1.500S\" type=\"static\" mediaPresentationDuration=\"PT0H0M7.500S\" maxSegmentDuration=\"PT0H0M2.000S\" profiles=\"urn:mpeg:dash:profile:isoff-on-demand:2011,http:\/\/dashif.org\/guidelines\/dash264\">\u003CPeriod duration=\"PT0H0M7.500S\">\u003CAdaptationSet segmentAlignment=\"true\" maxWidth=\"608\" maxHeight=\"1080\" maxFrameRate=\"24\" par=\"240:426\" lang=\"und\" subsegmentAlignment=\"true\" subsegmentStartsWithSAP=\"1\">\u003CRepresentation id=\"1537680713368685vd\" mimeType=\"video\/mp4\" codecs=\"avc1.4d401e\" width=\"240\" height=\"426\" frameRate=\"24\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"392003\" FBAbrPolicyTags=\"\" FBQualityClass=\"sd\" FBQualityLabel=\"240p\">\u003CBaseURL>https:\/\/video.xx.fbcdn.net\/v\/t42.1790-2\/17235555_1537680716702018_7107780415108153344_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ\u00253D\u00253D&amp;oh=6a04cc315c0eaa14b72c1af00a4d018f&amp;oe=5921EF2F\u003C\/BaseURL>\u003CSegmentBase indexRangeExact=\"true\" indexRange=\"939-1018\" FBFirstSegmentRange=\"1019-89473\">\u003CInitialization range=\"0-938\"\/>\u003C\/SegmentBase>\u003C\/Representation>\u003CRepresentation id=\"1537680690035354v\" mimeType=\"video\/mp4\" codecs=\"avc1.4d401e\" width=\"360\" height=\"640\" frameRate=\"24\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"737802\" FBAbrPolicyTags=\"hvq_mobile_landscape\" FBQualityClass=\"sd\" FBQualityLabel=\"360p\">\u003CBaseURL>https:\/\/video.xx.fbcdn.net\/v\/t42.1790-2\/17225640_1537680693368687_3499356447303532544_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNjQwX2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ\u00253D\u00253D&amp;oh=f91f8aef7b8ccc4387e775b7b173d0e6&amp;oe=5920F9FA\u003C\/BaseURL>\u003CSegmentBase indexRangeExact=\"true\" indexRange=\"939-1018\" FBFirstSegmentRange=\"1019-169177\">\u003CInitialization range=\"0-938\"\/>\u003C\/SegmentBase>\u003C\/Representation>\u003CRepresentation id=\"1537680736702016v\" mimeType=\"video\/mp4\" codecs=\"avc1.4d401e\" width=\"480\" height=\"854\" frameRate=\"24\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"1184491\" FBAbrPolicyTags=\"hvq_mobile_landscape\" FBQualityClass=\"sd\" FBQualityLabel=\"480p\">\u003CBaseURL>https:\/\/video.xx.fbcdn.net\/v\/t42.1790-2\/17182507_1537680740035349_9090482982757597184_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfODU0X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ\u00253D\u00253D&amp;oh=5beb3528c0bb8b8512e038803d5117e7&amp;oe=592108F5\u003C\/BaseURL>\u003CSegmentBase indexRangeExact=\"true\" indexRange=\"939-1018\" FBFirstSegmentRange=\"1019-272857\">\u003CInitialization range=\"0-938\"\/>\u003C\/SegmentBase>\u003C\/Representation>\u003C\/AdaptationSet>\u003C\/Period>\u003C\/MPD>\n","atom_size":2975,"bitrate":978400,"playable_duration_in_ms":7500},"message_owner":{"id":"100013803123634","name":"Facebook"},"message_text":"","time":1495212765}}]},"is_seen_by_viewer":false,"seenDirectUsers":{"edges":[{"node":{"id":"100006746883643","name":"Vin\u00edcius Pontin da Silva","short_name":"Vin\u00edcius","gender":"MALE"},"seen_time":1491129725}]},"direct_participants":{"edges":[{"node":{"id":"100006746883643","name":"Vin\u00edcius Pontin da Silva","short_name":"Vin\u00edcius","gender":"MALE"}}]}}},{"node":{"id":"481154312275156","time":1495212765,"thread_status":"PUBLISHED","direct_messages":{"edges":[{"node":{"id":"1938898123011732","url":null,"direct_message_type":"REGULAR","message_media":{"__typename":"Video","is_playable":true,"id":"1537679906702099","height":400,"width":224,"imageVideoThumbnail":{"height":720,"name":null,"scale":1,"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t15.0-10\/s720x720\/17237710_1537680530035370_4495076780167659520_n.jpg?oh=dfc701ae861890c3b403b148294be841&oe=59A31EDA","width":405},"playable_url":"https:\/\/video.xx.fbcdn.net\/v\/t43.1792-2\/17101051_1441927089153512_3825212648228651008_n.mp4?efg=eyJybHIiOjEyNjEsInJsYSI6NTEyLCJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&rl=1261&vabr=701&oh=c6fc4ca874fb7ce9acf09b6ead673bf7&oe=59212C73","dashPlayableURL":"https:\/\/graph.facebook.com\/video\/playback\/dash_mpd_debug.mpd?v=1537679906702099&dummy=.mpd","dashPlaylist":"\u003C?xml version=\"1.0\"?>\n\u003CMPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\" minBufferTime=\"PT1.500S\" type=\"static\" mediaPresentationDuration=\"PT0H0M6.667S\" maxSegmentDuration=\"PT0H0M2.000S\" profiles=\"urn:mpeg:dash:profile:isoff-on-demand:2011,http:\/\/dashif.org\/guidelines\/dash264\">\u003CPeriod duration=\"PT0H0M6.667S\">\u003CAdaptationSet segmentAlignment=\"true\" maxWidth=\"608\" maxHeight=\"1080\" maxFrameRate=\"24\" par=\"240:426\" lang=\"und\" subsegmentAlignment=\"true\" subsegmentStartsWithSAP=\"1\">\u003CRepresentation id=\"1537680633368693vd\" mimeType=\"video\/mp4\" codecs=\"avc1.4d401e\" width=\"240\" height=\"426\" frameRate=\"24\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"293870\" FBAbrPolicyTags=\"\" FBQualityClass=\"sd\" FBQualityLabel=\"240p\">\u003CBaseURL>https:\/\/video.xx.fbcdn.net\/v\/t42.1790-2\/17206735_1537680640035359_3894847653078368256_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ\u00253D\u00253D&amp;oh=b87e74267b4e0c1ff680cd9f493598c8&amp;oe=59222620\u003C\/BaseURL>\u003CSegmentBase indexRangeExact=\"true\" indexRange=\"939-1018\" FBFirstSegmentRange=\"1019-65921\">\u003CInitialization range=\"0-938\"\/>\u003C\/SegmentBase>\u003C\/Representation>\u003CRepresentation id=\"1537680683368688v\" mimeType=\"video\/mp4\" codecs=\"avc1.4d401e\" width=\"360\" height=\"640\" frameRate=\"24\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"512029\" FBAbrPolicyTags=\"hvq_mobile_landscape\" FBQualityClass=\"sd\" FBQualityLabel=\"360p\">\u003CBaseURL>https:\/\/video.xx.fbcdn.net\/v\/t42.1790-2\/17175122_1537680686702021_134018200999297024_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNjQwX2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ\u00253D\u00253D&amp;oh=8809e3ac09967ff52dae73b972f56a88&amp;oe=5921F362\u003C\/BaseURL>\u003CSegmentBase indexRangeExact=\"true\" indexRange=\"939-1018\" FBFirstSegmentRange=\"1019-115660\">\u003CInitialization range=\"0-938\"\/>\u003C\/SegmentBase>\u003C\/Representation>\u003CRepresentation id=\"1537680676702022v\" mimeType=\"video\/mp4\" codecs=\"avc1.4d401e\" width=\"480\" height=\"854\" frameRate=\"24\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"767487\" FBAbrPolicyTags=\"hvq_mobile_landscape\" FBQualityClass=\"sd\" FBQualityLabel=\"480p\">\u003CBaseURL>https:\/\/video.xx.fbcdn.net\/v\/t42.1790-2\/17183279_1537680680035355_4795597828007133184_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfODU0X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ\u00253D\u00253D&amp;oh=40f6577d8a5586dd27796b17f701be2b&amp;oe=59210095\u003C\/BaseURL>\u003CSegmentBase indexRangeExact=\"true\" indexRange=\"939-1018\" FBFirstSegmentRange=\"1019-175461\">\u003CInitialization range=\"0-938\"\/>\u003C\/SegmentBase>\u003C\/Representation>\u003C\/AdaptationSet>\u003C\/Period>\u003C\/MPD>\n","atom_size":2711,"bitrate":665046,"playable_duration_in_ms":6667},"message_owner":{"id":"100013803123634","name":"Facebook"},"message_text":"","time":1495212765}}]},"is_seen_by_viewer":false,"seenDirectUsers":{"edges":[]},"direct_participants":{"edges":[{"node":{"id":"100006746883643","name":"Vin\u00edcius Pontin da Silva","short_name":"Vin\u00edcius","gender":"MALE"}}]}}},{"node":{"id":"240788006394330","time":1495212765,"thread_status":"PUBLISHED","direct_messages":{"edges":[{"node":{"id":"1938898119678399","url":null,"direct_message_type":"REGULAR","message_media":{"__typename":"Video","is_playable":true,"id":"1537679703368786","height":400,"width":224,"imageVideoThumbnail":{"height":720,"name":null,"scale":1,"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t15.0-10\/s720x720\/17199677_1537680473368709_3456552545533558784_n.jpg?oh=2c140c764ca079695474ac2377831a51&oe=59A38903","width":405},"playable_url":"https:\/\/video.xx.fbcdn.net\/v\/t43.1792-2\/17104438_1383666405036810_7330383510588358656_n.mp4?efg=eyJybHIiOjk0MywicmxhIjo1MTIsInZlbmNvZGVfdGFnIjoic3ZlX2hkIn0\u00253D&rl=943&vabr=524&oh=47628940b008ae9e3a5d40dda5b1030d&oe=59211BE4","dashPlayableURL":"https:\/\/graph.facebook.com\/video\/playback\/dash_mpd_debug.mpd?v=1537679703368786&dummy=.mpd","dashPlaylist":"\u003C?xml version=\"1.0\"?>\n\u003CMPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\" minBufferTime=\"PT1.500S\" type=\"static\" mediaPresentationDuration=\"PT0H0M7.584S\" maxSegmentDuration=\"PT0H0M2.000S\" profiles=\"urn:mpeg:dash:profile:isoff-on-demand:2011,http:\/\/dashif.org\/guidelines\/dash264\">\u003CPeriod duration=\"PT0H0M7.584S\">\u003CAdaptationSet segmentAlignment=\"true\" maxWidth=\"608\" maxHeight=\"1080\" maxFrameRate=\"24\" par=\"240:426\" lang=\"und\" subsegmentAlignment=\"true\" subsegmentStartsWithSAP=\"1\">\u003CRepresentation id=\"1537680643368692vd\" mimeType=\"video\/mp4\" codecs=\"avc1.4d401e\" width=\"240\" height=\"426\" frameRate=\"24\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"176796\" FBAbrPolicyTags=\"\" FBQualityClass=\"sd\" FBQualityLabel=\"240p\">\u003CBaseURL>https:\/\/video.xx.fbcdn.net\/v\/t42.1790-2\/17227989_1537680646702025_6803779979902451712_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ\u00253D\u00253D&amp;oh=98d51e959e5013c6f5050d3e6a902d5b&amp;oe=5920DD7E\u003C\/BaseURL>\u003CSegmentBase indexRangeExact=\"true\" indexRange=\"939-1018\" FBFirstSegmentRange=\"1019-38238\">\u003CInitialization range=\"0-938\"\/>\u003C\/SegmentBase>\u003C\/Representation>\u003CRepresentation id=\"1537680653368691v\" mimeType=\"video\/mp4\" codecs=\"avc1.4d401e\" width=\"360\" height=\"640\" frameRate=\"24\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"319768\" FBAbrPolicyTags=\"hvq_mobile_landscape\" FBQualityClass=\"sd\" FBQualityLabel=\"360p\">\u003CBaseURL>https:\/\/video.xx.fbcdn.net\/v\/t42.1790-2\/17231533_1537680656702024_3036801019418771456_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNjQwX2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ\u00253D\u00253D&amp;oh=2769e25a613df3a9413aaa7292893f37&amp;oe=59221750\u003C\/BaseURL>\u003CSegmentBase indexRangeExact=\"true\" indexRange=\"939-1018\" FBFirstSegmentRange=\"1019-66818\">\u003CInitialization range=\"0-938\"\/>\u003C\/SegmentBase>\u003C\/Representation>\u003CRepresentation id=\"1537680723368684v\" mimeType=\"video\/mp4\" codecs=\"avc1.4d401e\" width=\"480\" height=\"854\" frameRate=\"24\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"513360\" FBAbrPolicyTags=\"hvq_mobile_landscape\" FBQualityClass=\"sd\" FBQualityLabel=\"480p\">\u003CBaseURL>https:\/\/video.xx.fbcdn.net\/v\/t42.1790-2\/17234568_1537680726702017_7697864468667039744_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfODU0X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ\u00253D\u00253D&amp;oh=68c94b30df13df3d1aac26f1299dacf9&amp;oe=5920ECBE\u003C\/BaseURL>\u003CSegmentBase indexRangeExact=\"true\" indexRange=\"939-1018\" FBFirstSegmentRange=\"1019-107949\">\u003CInitialization range=\"0-938\"\/>\u003C\/SegmentBase>\u003C\/Representation>\u003C\/AdaptationSet>\u003C\/Period>\u003C\/MPD>\n","atom_size":3003,"bitrate":493985,"playable_duration_in_ms":7584},"message_owner":{"id":"100013803123634","name":"Facebook"},"message_text":"","time":1495212765}}]},"is_seen_by_viewer":false,"seenDirectUsers":{"edges":[{"node":{"id":"100006746883643","name":"Vin\u00edcius Pontin da Silva","short_name":"Vin\u00edcius","gender":"MALE"},"seen_time":1492032052}]},"direct_participants":{"edges":[{"node":{"id":"100006746883643","name":"Vin\u00edcius Pontin da Silva","short_name":"Vin\u00edcius","gender":"MALE"}}]}}}]},"latest_thread_creation_time":1491076399,"unseen_count":3,"live_video":null}},{"score":0.5047498569566,"tracking_string":"{\"request_id\":\"ca1aaf8b-0b64-44a9-af87-e3a9d75e6e9f\",\"bucket_id\":\"1281945271842557\",\"owner_id\":\"1769665113\"}","node":{"id":"1281945271842557","is_tutorial":false,"other_participant":{"id":"1769665113","name":"Angel Abreu","short_name":"Angel","gender":"FEMALE"},"threads":{"edges":[{"node":{"id":"1889415371318822","time":1495201662,"thread_status":"PUBLISHED","direct_messages":{"edges":[{"node":{"id":"10203589841944519","url":null,"direct_message_type":"REGULAR","message_media":{"__typename":"Photo","is_playable":false,"id":"10203589841624511","image150":{"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-0\/s160x160\/18527914_10203589841624511_1346510800460502919_n.jpg?oh=2783c61dc71074d22f314c096feb10ef&oe=59749C52"},"image960":{"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-9\/18527914_10203589841624511_1346510800460502919_n.jpg?oh=37780ff42a3e0fcb11e71ccc23f460d9&oe=59AD6E90"},"image2048":{"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t31.0-8\/18518253_10203589841624511_1346510800460502919_o.jpg?oh=1eb99d17e5c22e9eae1be2239d342bb8&oe=59B81ED0"}},"message_owner":{"id":"1769665113","name":"Angel Abreu"},"message_text":"","time":1495201662}}]},"is_seen_by_viewer":false,"seenDirectUsers":{"edges":[{"node":{"id":"100000208059134","name":"Daniela Monticelli Teixeira","short_name":"Daniela","gender":"FEMALE"},"seen_time":1495204723},{"node":{"id":"100001358372947","name":"Camila Barruffe","short_name":"Camila","gender":"FEMALE"},"seen_time":1495204615},{"node":{"id":"100007089098808","name":"Emmanuelle Abreu","short_name":"Emmanuelle","gender":"FEMALE"},"seen_time":1495202432},{"node":{"id":"100007973864499","name":"Dig Anuncia\u00e7\u00e3o Martins","short_name":"Dig","gender":"MALE"},"seen_time":1495202090}]},"direct_participants":{"edges":[{"node":{"id":"100000208059134","name":"Daniela Monticelli Teixeira","short_name":"Daniela","gender":"FEMALE"}},{"node":{"id":"1769665113","name":"Angel Abreu","short_name":"Angel","gender":"FEMALE"}},{"node":{"id":"100001358372947","name":"Camila Barruffe","short_name":"Camila","gender":"FEMALE"}},{"node":{"id":"100007089098808","name":"Emmanuelle Abreu","short_name":"Emmanuelle","gender":"FEMALE"}},{"node":{"id":"100007973864499","name":"Dig Anuncia\u00e7\u00e3o Martins","short_name":"Dig","gender":"MALE"}}]}}}]},"latest_thread_creation_time":1495201662,"unseen_count":1,"live_video":null}}]}}},"error":null,"query_id":1237133843001937}}
{"successful_results":1,"error_results":0,"skipped_results":0}
`

**Comment by CaliAlec** [comment]
@vpontin I've fixed the issue. Please try the new attachment.
[ChromeFBStory.zip](https://github.com/CaliAlec/ChromeFBStory/files/1014998/ChromeFBStory.zip)

**Comment by vpontin** [comment]
Worked like a charm! Thanks a lot!!!
