### ISSUE TITLE
Stories won't load

### ISSUE THREAD

**Issue by vpontin** [CaliAlec/ChromeFBStory#2]
Hi!
I'm just reinstalled the extension you've provided for me in #1 , but this time every time i try to load a facebook tab no stories appears in the feed.

Going in the Console tab in developer tools i see this only error:

```
Uncaught (in promise) TypeError: Cannot read property '1' of null
    at parseAccessToken (chrome-extension://phfjaioohlomleaaehkjblpbjkaogmfj/js/content.js:51416)
    at <anonymous>
```

Did Facebook broke something in a recent update?

Thanks in advance!

**Comment by CaliAlec** [comment]
@vpontin Yes, Facebook changed something and the method I was using to retrieve the access token no longer works. Need to research a workaround.

**Comment by CaliAlec** [comment]
Fixed in https://github.com/CaliAlec/ChromeFBStory/commit/a5c69ddf8e523cbb17d8f2315ddd53d91aa2e3e5

**Comment by vpontin** [comment]
Thanks a lot!
