### ISSUE TITLE
Is this still maintained? I had no luck getting it to run :(

### ISSUE THREAD

**Issue by wormeyman** [CaliAlec/ChromeFBStory#4]
My guess is because i am running node version 8 on my ubuntu WSL install.

**Comment by CaliAlec** [comment]
@wormeyman It's currently not maintained. Facebook sent me a cease and desist letter which got the extension taken down from the Chrome Web Store. Facebook officially brought Stories to desktop so maintaining this extension isn't a high priority for me right now.
